#!/usr/bin/env node
/* eslint-disable no-console */

const path = require('path');
const { onMsg, onError, onSuccess, npmCmd } = require('./_helpers');

Promise.all([
    npmCmd('lint').catch(error=>{
        onError([
            'Oops! you have linting errors. Sort them out by running:',
            chalk.bgWhite.bold.black('npm run fix')
        ])
        throw error;
    }),
    npmCmd('flow').catch(error=>{
        onError([
            'Oops! you have type errors',
            chalkrw('good luck')
        ])
        throw error;
    })
]).catch(()=>{
    process.exit(1);
}).then(()=>{
    onSuccess(['Your JS linting & typing looks great!']);
    process.exit(0);
})
