#!/usr/bin/env node
/* eslint-disable no-console */

const path = require('path');
const execa = require('execa');
const chalk = require('chalk');

execa('npm', ['run','lint'], {
  stdio: 'inherit',
}).catch(error=>{
  console.log("\n\n");
  console.log(chalk.red('🙅   Oops! you have linting errors. Sort them out by running:'));
  console.log('    '+chalk.bgWhite.bold.black('npm run fix'));
  console.log("\n\n");
})
