#!/bin/bash
JAVA_PATH="/usr/lib/jvm/java-1.8.0/"

echo ''
echo "********************************* JAVA VERSION *********************************"
"${JAVA_PATH}/bin/java" -version
echo "********************************************************************************"
echo ''

export JAVA_HOME="${JAVA_PATH}/bin/java"
export JDK_HOME="${JAVA_PATH}/bin/java"

cat /dev/null | "${JAVA_PATH}/bin/java" -Xmx1384M -XX:MaxMetaspaceSize=384M -XX:+UseCompressedOops \
    -jar sbt-launch.jar "$@"