// flow-typed signature: 67b817a69bba1fe8315108e888a708a7
// flow-typed version: <<STUB>>/chalk-rainbow_v^1.0.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chalk-rainbow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chalk-rainbow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chalk-rainbow/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chalk-rainbow/index' {
  declare module.exports: $Exports<'chalk-rainbow'>;
}
declare module 'chalk-rainbow/index.js' {
  declare module.exports: $Exports<'chalk-rainbow'>;
}
declare module 'chalk-rainbow/test.js' {
  declare module.exports: $Exports<'chalk-rainbow/test'>;
}
