// flow-typed signature: dcad06fe64b5e514ae6244c52b596b83
// flow-typed version: <<STUB>>/cookie-cutter_v^0.1.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cookie-cutter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cookie-cutter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cookie-cutter/example/getset/main' {
  declare module.exports: any;
}

declare module 'cookie-cutter/example/getset/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cookie-cutter/example/getset/main.js' {
  declare module.exports: $Exports<'cookie-cutter/example/getset/main'>;
}
declare module 'cookie-cutter/example/getset/server.js' {
  declare module.exports: $Exports<'cookie-cutter/example/getset/server'>;
}
declare module 'cookie-cutter/index' {
  declare module.exports: $Exports<'cookie-cutter'>;
}
declare module 'cookie-cutter/index.js' {
  declare module.exports: $Exports<'cookie-cutter'>;
}
