// flow-typed signature: 9b140853db109490c2e38bbc76a2f56e
// flow-typed version: <<STUB>>/curl-amd_v^0.8.12/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'curl-amd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'curl-amd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'curl-amd/dist/curl-for-dojo1.6/curl' {
  declare module.exports: any;
}

declare module 'curl-amd/dist/curl-for-dojo1.8/curl' {
  declare module.exports: any;
}

declare module 'curl-amd/dist/curl-for-jQuery/curl' {
  declare module.exports: any;
}

declare module 'curl-amd/dist/curl-for-ssjs/curl' {
  declare module.exports: any;
}

declare module 'curl-amd/dist/curl-kitchen-sink/curl' {
  declare module.exports: any;
}

declare module 'curl-amd/dist/curl-with-js-and-domReady/curl' {
  declare module.exports: any;
}

declare module 'curl-amd/dist/curl/curl' {
  declare module.exports: any;
}

declare module 'curl-amd/dist/debug/curl' {
  declare module.exports: any;
}

declare module 'curl-amd/src/cram-client' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl-bak' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/cram/_define' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/cram/_stringify' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/cram/cjsm11' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/cram/css' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/cram/i18n' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/cram/js' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/cram/jsEncode' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/cram/json' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/cram/legacy' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/cram/text' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/debug' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/domReady' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/loader/cjsm11' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/loader/legacy' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/plugin/_fetchText' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/plugin/async' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/plugin/css' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/plugin/domReady' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/plugin/i18n' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/plugin/img' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/plugin/js' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/plugin/json' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/plugin/link' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/plugin/locale' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/plugin/style' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/plugin/text' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/shim/_fetchText' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/shim/dojo16' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/shim/dojo18' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/shim/ssjs' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/tdd/runner' {
  declare module.exports: any;
}

declare module 'curl-amd/src/curl/tdd/undefine' {
  declare module.exports: any;
}

declare module 'curl-amd/test/i18n/strings' {
  declare module.exports: any;
}

declare module 'curl-amd/test/i18n/strings/en-gb' {
  declare module.exports: any;
}

declare module 'curl-amd/test/stuff/aView/controller' {
  declare module.exports: any;
}

declare module 'curl-amd/test/stuff/css-on-cdn' {
  declare module.exports: any;
}

declare module 'curl-amd/test/stuff/dep-on-test1-in-define' {
  declare module.exports: any;
}

declare module 'curl-amd/test/stuff/dep-on-test1' {
  declare module.exports: any;
}

declare module 'curl-amd/test/stuff/foo.defineModule' {
  declare module.exports: any;
}

declare module 'curl-amd/test/stuff/increments' {
  declare module.exports: any;
}

declare module 'curl-amd/test/stuff/issue53' {
  declare module.exports: any;
}

declare module 'curl-amd/test/stuff/nls/strings' {
  declare module.exports: any;
}

declare module 'curl-amd/test/stuff/one' {
  declare module.exports: any;
}

declare module 'curl-amd/test/stuff/plain_old_2' {
  declare module.exports: any;
}

declare module 'curl-amd/test/stuff/plain_old' {
  declare module.exports: any;
}

declare module 'curl-amd/test/stuff/random' {
  declare module.exports: any;
}

declare module 'curl-amd/test/stuff/run-script' {
  declare module.exports: any;
}

declare module 'curl-amd/test/stuff/three' {
  declare module.exports: any;
}

declare module 'curl-amd/test/stuff/two' {
  declare module.exports: any;
}

declare module 'curl-amd/test/stuff/undefined-module' {
  declare module.exports: any;
}

declare module 'curl-amd/test/stuff/wants-js-and-css' {
  declare module.exports: any;
}

declare module 'curl-amd/test/stuff/zero' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/commonjs/exports' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/commonjs/folder/deep/returnMain' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/commonjs/folder/non-cjs' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/commonjs/folder/returnMain' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/commonjs/foo' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/commonjs/hybrid' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/commonjs/loop/hybrid-loop1' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/commonjs/loop/hybrid-loop2' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/commonjs/loop/hybrid-loop3' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/commonjs/main-with-relative-dep' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/commonjs/main' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/commonjs/main2' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/commonjs/module' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/commonjs/nakedDependentCjsm1.1' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/commonjs/nakedSimpleCjsm1.1' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/commonjs/named-main' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/commonjs/relative-dep' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/commonjs/return-config' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/commonjs/this' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/fake' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/foo-bar-define/simple' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/loop/loop-start' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/loop/loop1' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/loop/loop2' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/loop/loop3' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/main-plugin' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/requires-fake' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/simple-plugin' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/underscore-amdjs-1.3.1/underscore-min' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/underscore-amdjs-1.3.1/underscore-orig' {
  declare module.exports: any;
}

declare module 'curl-amd/test/support/underscore-amdjs-1.3.1/underscore' {
  declare module.exports: any;
}

declare module 'curl-amd/test/tdd/configureAsserts' {
  declare module.exports: any;
}

declare module 'curl-amd/test/tdd/MethodSpy' {
  declare module.exports: any;
}

declare module 'curl-amd/test/tdd/Spy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'curl-amd/dist/curl-for-dojo1.6/curl.js' {
  declare module.exports: $Exports<'curl-amd/dist/curl-for-dojo1.6/curl'>;
}
declare module 'curl-amd/dist/curl-for-dojo1.8/curl.js' {
  declare module.exports: $Exports<'curl-amd/dist/curl-for-dojo1.8/curl'>;
}
declare module 'curl-amd/dist/curl-for-jQuery/curl.js' {
  declare module.exports: $Exports<'curl-amd/dist/curl-for-jQuery/curl'>;
}
declare module 'curl-amd/dist/curl-for-ssjs/curl.js' {
  declare module.exports: $Exports<'curl-amd/dist/curl-for-ssjs/curl'>;
}
declare module 'curl-amd/dist/curl-kitchen-sink/curl.js' {
  declare module.exports: $Exports<'curl-amd/dist/curl-kitchen-sink/curl'>;
}
declare module 'curl-amd/dist/curl-with-js-and-domReady/curl.js' {
  declare module.exports: $Exports<'curl-amd/dist/curl-with-js-and-domReady/curl'>;
}
declare module 'curl-amd/dist/curl/curl.js' {
  declare module.exports: $Exports<'curl-amd/dist/curl/curl'>;
}
declare module 'curl-amd/dist/debug/curl.js' {
  declare module.exports: $Exports<'curl-amd/dist/debug/curl'>;
}
declare module 'curl-amd/src/cram-client.js' {
  declare module.exports: $Exports<'curl-amd/src/cram-client'>;
}
declare module 'curl-amd/src/curl-bak.js' {
  declare module.exports: $Exports<'curl-amd/src/curl-bak'>;
}
declare module 'curl-amd/src/curl.js' {
  declare module.exports: $Exports<'curl-amd/src/curl'>;
}
declare module 'curl-amd/src/curl/cram/_define.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/cram/_define'>;
}
declare module 'curl-amd/src/curl/cram/_stringify.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/cram/_stringify'>;
}
declare module 'curl-amd/src/curl/cram/cjsm11.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/cram/cjsm11'>;
}
declare module 'curl-amd/src/curl/cram/css.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/cram/css'>;
}
declare module 'curl-amd/src/curl/cram/i18n.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/cram/i18n'>;
}
declare module 'curl-amd/src/curl/cram/js.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/cram/js'>;
}
declare module 'curl-amd/src/curl/cram/jsEncode.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/cram/jsEncode'>;
}
declare module 'curl-amd/src/curl/cram/json.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/cram/json'>;
}
declare module 'curl-amd/src/curl/cram/legacy.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/cram/legacy'>;
}
declare module 'curl-amd/src/curl/cram/text.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/cram/text'>;
}
declare module 'curl-amd/src/curl/debug.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/debug'>;
}
declare module 'curl-amd/src/curl/domReady.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/domReady'>;
}
declare module 'curl-amd/src/curl/loader/cjsm11.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/loader/cjsm11'>;
}
declare module 'curl-amd/src/curl/loader/legacy.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/loader/legacy'>;
}
declare module 'curl-amd/src/curl/plugin/_fetchText.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/plugin/_fetchText'>;
}
declare module 'curl-amd/src/curl/plugin/async.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/plugin/async'>;
}
declare module 'curl-amd/src/curl/plugin/css.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/plugin/css'>;
}
declare module 'curl-amd/src/curl/plugin/domReady.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/plugin/domReady'>;
}
declare module 'curl-amd/src/curl/plugin/i18n.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/plugin/i18n'>;
}
declare module 'curl-amd/src/curl/plugin/img.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/plugin/img'>;
}
declare module 'curl-amd/src/curl/plugin/js.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/plugin/js'>;
}
declare module 'curl-amd/src/curl/plugin/json.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/plugin/json'>;
}
declare module 'curl-amd/src/curl/plugin/link.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/plugin/link'>;
}
declare module 'curl-amd/src/curl/plugin/locale.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/plugin/locale'>;
}
declare module 'curl-amd/src/curl/plugin/style.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/plugin/style'>;
}
declare module 'curl-amd/src/curl/plugin/text.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/plugin/text'>;
}
declare module 'curl-amd/src/curl/shim/_fetchText.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/shim/_fetchText'>;
}
declare module 'curl-amd/src/curl/shim/dojo16.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/shim/dojo16'>;
}
declare module 'curl-amd/src/curl/shim/dojo18.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/shim/dojo18'>;
}
declare module 'curl-amd/src/curl/shim/ssjs.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/shim/ssjs'>;
}
declare module 'curl-amd/src/curl/tdd/runner.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/tdd/runner'>;
}
declare module 'curl-amd/src/curl/tdd/undefine.js' {
  declare module.exports: $Exports<'curl-amd/src/curl/tdd/undefine'>;
}
declare module 'curl-amd/test/i18n/strings.js' {
  declare module.exports: $Exports<'curl-amd/test/i18n/strings'>;
}
declare module 'curl-amd/test/i18n/strings/en-gb.js' {
  declare module.exports: $Exports<'curl-amd/test/i18n/strings/en-gb'>;
}
declare module 'curl-amd/test/stuff/aView/controller.js' {
  declare module.exports: $Exports<'curl-amd/test/stuff/aView/controller'>;
}
declare module 'curl-amd/test/stuff/css-on-cdn.js' {
  declare module.exports: $Exports<'curl-amd/test/stuff/css-on-cdn'>;
}
declare module 'curl-amd/test/stuff/dep-on-test1-in-define.js' {
  declare module.exports: $Exports<'curl-amd/test/stuff/dep-on-test1-in-define'>;
}
declare module 'curl-amd/test/stuff/dep-on-test1.js' {
  declare module.exports: $Exports<'curl-amd/test/stuff/dep-on-test1'>;
}
declare module 'curl-amd/test/stuff/foo.defineModule.js' {
  declare module.exports: $Exports<'curl-amd/test/stuff/foo.defineModule'>;
}
declare module 'curl-amd/test/stuff/increments.js' {
  declare module.exports: $Exports<'curl-amd/test/stuff/increments'>;
}
declare module 'curl-amd/test/stuff/issue53.js' {
  declare module.exports: $Exports<'curl-amd/test/stuff/issue53'>;
}
declare module 'curl-amd/test/stuff/nls/strings.js' {
  declare module.exports: $Exports<'curl-amd/test/stuff/nls/strings'>;
}
declare module 'curl-amd/test/stuff/one.js' {
  declare module.exports: $Exports<'curl-amd/test/stuff/one'>;
}
declare module 'curl-amd/test/stuff/plain_old_2.js' {
  declare module.exports: $Exports<'curl-amd/test/stuff/plain_old_2'>;
}
declare module 'curl-amd/test/stuff/plain_old.js' {
  declare module.exports: $Exports<'curl-amd/test/stuff/plain_old'>;
}
declare module 'curl-amd/test/stuff/random.js' {
  declare module.exports: $Exports<'curl-amd/test/stuff/random'>;
}
declare module 'curl-amd/test/stuff/run-script.js' {
  declare module.exports: $Exports<'curl-amd/test/stuff/run-script'>;
}
declare module 'curl-amd/test/stuff/three.js' {
  declare module.exports: $Exports<'curl-amd/test/stuff/three'>;
}
declare module 'curl-amd/test/stuff/two.js' {
  declare module.exports: $Exports<'curl-amd/test/stuff/two'>;
}
declare module 'curl-amd/test/stuff/undefined-module.js' {
  declare module.exports: $Exports<'curl-amd/test/stuff/undefined-module'>;
}
declare module 'curl-amd/test/stuff/wants-js-and-css.js' {
  declare module.exports: $Exports<'curl-amd/test/stuff/wants-js-and-css'>;
}
declare module 'curl-amd/test/stuff/zero.js' {
  declare module.exports: $Exports<'curl-amd/test/stuff/zero'>;
}
declare module 'curl-amd/test/support/commonjs/exports.js' {
  declare module.exports: $Exports<'curl-amd/test/support/commonjs/exports'>;
}
declare module 'curl-amd/test/support/commonjs/folder/deep/returnMain.js' {
  declare module.exports: $Exports<'curl-amd/test/support/commonjs/folder/deep/returnMain'>;
}
declare module 'curl-amd/test/support/commonjs/folder/non-cjs.js' {
  declare module.exports: $Exports<'curl-amd/test/support/commonjs/folder/non-cjs'>;
}
declare module 'curl-amd/test/support/commonjs/folder/returnMain.js' {
  declare module.exports: $Exports<'curl-amd/test/support/commonjs/folder/returnMain'>;
}
declare module 'curl-amd/test/support/commonjs/foo.js' {
  declare module.exports: $Exports<'curl-amd/test/support/commonjs/foo'>;
}
declare module 'curl-amd/test/support/commonjs/hybrid.js' {
  declare module.exports: $Exports<'curl-amd/test/support/commonjs/hybrid'>;
}
declare module 'curl-amd/test/support/commonjs/loop/hybrid-loop1.js' {
  declare module.exports: $Exports<'curl-amd/test/support/commonjs/loop/hybrid-loop1'>;
}
declare module 'curl-amd/test/support/commonjs/loop/hybrid-loop2.js' {
  declare module.exports: $Exports<'curl-amd/test/support/commonjs/loop/hybrid-loop2'>;
}
declare module 'curl-amd/test/support/commonjs/loop/hybrid-loop3.js' {
  declare module.exports: $Exports<'curl-amd/test/support/commonjs/loop/hybrid-loop3'>;
}
declare module 'curl-amd/test/support/commonjs/main-with-relative-dep.js' {
  declare module.exports: $Exports<'curl-amd/test/support/commonjs/main-with-relative-dep'>;
}
declare module 'curl-amd/test/support/commonjs/main.js' {
  declare module.exports: $Exports<'curl-amd/test/support/commonjs/main'>;
}
declare module 'curl-amd/test/support/commonjs/main2.js' {
  declare module.exports: $Exports<'curl-amd/test/support/commonjs/main2'>;
}
declare module 'curl-amd/test/support/commonjs/module.js' {
  declare module.exports: $Exports<'curl-amd/test/support/commonjs/module'>;
}
declare module 'curl-amd/test/support/commonjs/nakedDependentCjsm1.1.js' {
  declare module.exports: $Exports<'curl-amd/test/support/commonjs/nakedDependentCjsm1.1'>;
}
declare module 'curl-amd/test/support/commonjs/nakedSimpleCjsm1.1.js' {
  declare module.exports: $Exports<'curl-amd/test/support/commonjs/nakedSimpleCjsm1.1'>;
}
declare module 'curl-amd/test/support/commonjs/named-main.js' {
  declare module.exports: $Exports<'curl-amd/test/support/commonjs/named-main'>;
}
declare module 'curl-amd/test/support/commonjs/relative-dep.js' {
  declare module.exports: $Exports<'curl-amd/test/support/commonjs/relative-dep'>;
}
declare module 'curl-amd/test/support/commonjs/return-config.js' {
  declare module.exports: $Exports<'curl-amd/test/support/commonjs/return-config'>;
}
declare module 'curl-amd/test/support/commonjs/this.js' {
  declare module.exports: $Exports<'curl-amd/test/support/commonjs/this'>;
}
declare module 'curl-amd/test/support/fake.js' {
  declare module.exports: $Exports<'curl-amd/test/support/fake'>;
}
declare module 'curl-amd/test/support/foo-bar-define/simple.js' {
  declare module.exports: $Exports<'curl-amd/test/support/foo-bar-define/simple'>;
}
declare module 'curl-amd/test/support/loop/loop-start.js' {
  declare module.exports: $Exports<'curl-amd/test/support/loop/loop-start'>;
}
declare module 'curl-amd/test/support/loop/loop1.js' {
  declare module.exports: $Exports<'curl-amd/test/support/loop/loop1'>;
}
declare module 'curl-amd/test/support/loop/loop2.js' {
  declare module.exports: $Exports<'curl-amd/test/support/loop/loop2'>;
}
declare module 'curl-amd/test/support/loop/loop3.js' {
  declare module.exports: $Exports<'curl-amd/test/support/loop/loop3'>;
}
declare module 'curl-amd/test/support/main-plugin.js' {
  declare module.exports: $Exports<'curl-amd/test/support/main-plugin'>;
}
declare module 'curl-amd/test/support/requires-fake.js' {
  declare module.exports: $Exports<'curl-amd/test/support/requires-fake'>;
}
declare module 'curl-amd/test/support/simple-plugin.js' {
  declare module.exports: $Exports<'curl-amd/test/support/simple-plugin'>;
}
declare module 'curl-amd/test/support/underscore-amdjs-1.3.1/underscore-min.js' {
  declare module.exports: $Exports<'curl-amd/test/support/underscore-amdjs-1.3.1/underscore-min'>;
}
declare module 'curl-amd/test/support/underscore-amdjs-1.3.1/underscore-orig.js' {
  declare module.exports: $Exports<'curl-amd/test/support/underscore-amdjs-1.3.1/underscore-orig'>;
}
declare module 'curl-amd/test/support/underscore-amdjs-1.3.1/underscore.js' {
  declare module.exports: $Exports<'curl-amd/test/support/underscore-amdjs-1.3.1/underscore'>;
}
declare module 'curl-amd/test/tdd/configureAsserts.js' {
  declare module.exports: $Exports<'curl-amd/test/tdd/configureAsserts'>;
}
declare module 'curl-amd/test/tdd/MethodSpy.js' {
  declare module.exports: $Exports<'curl-amd/test/tdd/MethodSpy'>;
}
declare module 'curl-amd/test/tdd/Spy.js' {
  declare module.exports: $Exports<'curl-amd/test/tdd/Spy'>;
}
