// flow-typed signature: d83840b17bfec6db691058e886c0a3e4
// flow-typed version: <<STUB>>/intl-tel-input_v^9.0.9/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'intl-tel-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'intl-tel-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'intl-tel-input/build/js/intlTelInput' {
  declare module.exports: any;
}

declare module 'intl-tel-input/build/js/intlTelInput.min' {
  declare module.exports: any;
}

declare module 'intl-tel-input/build/js/utils' {
  declare module.exports: any;
}

declare module 'intl-tel-input/examples/js/countrySync' {
  declare module.exports: any;
}

declare module 'intl-tel-input/examples/js/defaultCountryIp' {
  declare module.exports: any;
}

declare module 'intl-tel-input/examples/js/hiddenInput' {
  declare module.exports: any;
}

declare module 'intl-tel-input/examples/js/isValidNumber' {
  declare module.exports: any;
}

declare module 'intl-tel-input/examples/js/modifyCountryData' {
  declare module.exports: any;
}

declare module 'intl-tel-input/examples/js/nationalMode' {
  declare module.exports: any;
}

declare module 'intl-tel-input/examples/js/onlyCountriesEurope' {
  declare module.exports: any;
}

declare module 'intl-tel-input/examples/js/prism' {
  declare module.exports: any;
}

declare module 'intl-tel-input/grunt/bump' {
  declare module.exports: any;
}

declare module 'intl-tel-input/grunt/exec' {
  declare module.exports: any;
}

declare module 'intl-tel-input/grunt/imagemin' {
  declare module.exports: any;
}

declare module 'intl-tel-input/grunt/jasmine' {
  declare module.exports: any;
}

declare module 'intl-tel-input/grunt/jshint' {
  declare module.exports: any;
}

declare module 'intl-tel-input/grunt/replace' {
  declare module.exports: any;
}

declare module 'intl-tel-input/grunt/responsive_images' {
  declare module.exports: any;
}

declare module 'intl-tel-input/grunt/retinafy' {
  declare module.exports: any;
}

declare module 'intl-tel-input/grunt/sass' {
  declare module.exports: any;
}

declare module 'intl-tel-input/grunt/shell' {
  declare module.exports: any;
}

declare module 'intl-tel-input/grunt/sprite' {
  declare module.exports: any;
}

declare module 'intl-tel-input/grunt/template' {
  declare module.exports: any;
}

declare module 'intl-tel-input/grunt/uglify' {
  declare module.exports: any;
}

declare module 'intl-tel-input/grunt/watch' {
  declare module.exports: any;
}

declare module 'intl-tel-input/Gruntfile' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/js/data' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/js/utils' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/helpers/helpers' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/core/countrychangeEvent' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/core/dropdownShortcuts' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/core/initialValues' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/core/multipleInstances' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/core/usingDropdown' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/core/usingInput' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/methods/destroy' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/methods/getExtension' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/methods/getNumber' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/methods/getNumberType' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/methods/getSelectedCountryData' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/methods/getValidationError' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/methods/isValidNumber' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/methods/setCountry' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/methods/setNumber' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/options/allowDropdown' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/options/autoHideDialCode' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/options/autoPlaceholder' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/options/customPlaceholder' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/options/dropdownContainer' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/options/excludeCountries' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/options/formatOnInit' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/options/geoIpLookup' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/options/initialCountry' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/options/nationalMode' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/options/numberType' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/options/onlyCountries' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/options/preferredCountries' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/options/separateDialCode' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/options/utilsScript' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/static/defaults' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/static/getCountryData' {
  declare module.exports: any;
}

declare module 'intl-tel-input/src/spec/tests/static/loadUtils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'intl-tel-input/build/js/intlTelInput.js' {
  declare module.exports: $Exports<'intl-tel-input/build/js/intlTelInput'>;
}
declare module 'intl-tel-input/build/js/intlTelInput.min.js' {
  declare module.exports: $Exports<'intl-tel-input/build/js/intlTelInput.min'>;
}
declare module 'intl-tel-input/build/js/utils.js' {
  declare module.exports: $Exports<'intl-tel-input/build/js/utils'>;
}
declare module 'intl-tel-input/examples/js/countrySync.js' {
  declare module.exports: $Exports<'intl-tel-input/examples/js/countrySync'>;
}
declare module 'intl-tel-input/examples/js/defaultCountryIp.js' {
  declare module.exports: $Exports<'intl-tel-input/examples/js/defaultCountryIp'>;
}
declare module 'intl-tel-input/examples/js/hiddenInput.js' {
  declare module.exports: $Exports<'intl-tel-input/examples/js/hiddenInput'>;
}
declare module 'intl-tel-input/examples/js/isValidNumber.js' {
  declare module.exports: $Exports<'intl-tel-input/examples/js/isValidNumber'>;
}
declare module 'intl-tel-input/examples/js/modifyCountryData.js' {
  declare module.exports: $Exports<'intl-tel-input/examples/js/modifyCountryData'>;
}
declare module 'intl-tel-input/examples/js/nationalMode.js' {
  declare module.exports: $Exports<'intl-tel-input/examples/js/nationalMode'>;
}
declare module 'intl-tel-input/examples/js/onlyCountriesEurope.js' {
  declare module.exports: $Exports<'intl-tel-input/examples/js/onlyCountriesEurope'>;
}
declare module 'intl-tel-input/examples/js/prism.js' {
  declare module.exports: $Exports<'intl-tel-input/examples/js/prism'>;
}
declare module 'intl-tel-input/grunt/bump.js' {
  declare module.exports: $Exports<'intl-tel-input/grunt/bump'>;
}
declare module 'intl-tel-input/grunt/exec.js' {
  declare module.exports: $Exports<'intl-tel-input/grunt/exec'>;
}
declare module 'intl-tel-input/grunt/imagemin.js' {
  declare module.exports: $Exports<'intl-tel-input/grunt/imagemin'>;
}
declare module 'intl-tel-input/grunt/jasmine.js' {
  declare module.exports: $Exports<'intl-tel-input/grunt/jasmine'>;
}
declare module 'intl-tel-input/grunt/jshint.js' {
  declare module.exports: $Exports<'intl-tel-input/grunt/jshint'>;
}
declare module 'intl-tel-input/grunt/replace.js' {
  declare module.exports: $Exports<'intl-tel-input/grunt/replace'>;
}
declare module 'intl-tel-input/grunt/responsive_images.js' {
  declare module.exports: $Exports<'intl-tel-input/grunt/responsive_images'>;
}
declare module 'intl-tel-input/grunt/retinafy.js' {
  declare module.exports: $Exports<'intl-tel-input/grunt/retinafy'>;
}
declare module 'intl-tel-input/grunt/sass.js' {
  declare module.exports: $Exports<'intl-tel-input/grunt/sass'>;
}
declare module 'intl-tel-input/grunt/shell.js' {
  declare module.exports: $Exports<'intl-tel-input/grunt/shell'>;
}
declare module 'intl-tel-input/grunt/sprite.js' {
  declare module.exports: $Exports<'intl-tel-input/grunt/sprite'>;
}
declare module 'intl-tel-input/grunt/template.js' {
  declare module.exports: $Exports<'intl-tel-input/grunt/template'>;
}
declare module 'intl-tel-input/grunt/uglify.js' {
  declare module.exports: $Exports<'intl-tel-input/grunt/uglify'>;
}
declare module 'intl-tel-input/grunt/watch.js' {
  declare module.exports: $Exports<'intl-tel-input/grunt/watch'>;
}
declare module 'intl-tel-input/Gruntfile.js' {
  declare module.exports: $Exports<'intl-tel-input/Gruntfile'>;
}
declare module 'intl-tel-input/index' {
  declare module.exports: $Exports<'intl-tel-input'>;
}
declare module 'intl-tel-input/index.js' {
  declare module.exports: $Exports<'intl-tel-input'>;
}
declare module 'intl-tel-input/src/js/data.js' {
  declare module.exports: $Exports<'intl-tel-input/src/js/data'>;
}
declare module 'intl-tel-input/src/js/utils.js' {
  declare module.exports: $Exports<'intl-tel-input/src/js/utils'>;
}
declare module 'intl-tel-input/src/spec/helpers/helpers.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/helpers/helpers'>;
}
declare module 'intl-tel-input/src/spec/tests/core/countrychangeEvent.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/core/countrychangeEvent'>;
}
declare module 'intl-tel-input/src/spec/tests/core/dropdownShortcuts.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/core/dropdownShortcuts'>;
}
declare module 'intl-tel-input/src/spec/tests/core/initialValues.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/core/initialValues'>;
}
declare module 'intl-tel-input/src/spec/tests/core/multipleInstances.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/core/multipleInstances'>;
}
declare module 'intl-tel-input/src/spec/tests/core/usingDropdown.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/core/usingDropdown'>;
}
declare module 'intl-tel-input/src/spec/tests/core/usingInput.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/core/usingInput'>;
}
declare module 'intl-tel-input/src/spec/tests/methods/destroy.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/methods/destroy'>;
}
declare module 'intl-tel-input/src/spec/tests/methods/getExtension.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/methods/getExtension'>;
}
declare module 'intl-tel-input/src/spec/tests/methods/getNumber.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/methods/getNumber'>;
}
declare module 'intl-tel-input/src/spec/tests/methods/getNumberType.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/methods/getNumberType'>;
}
declare module 'intl-tel-input/src/spec/tests/methods/getSelectedCountryData.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/methods/getSelectedCountryData'>;
}
declare module 'intl-tel-input/src/spec/tests/methods/getValidationError.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/methods/getValidationError'>;
}
declare module 'intl-tel-input/src/spec/tests/methods/isValidNumber.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/methods/isValidNumber'>;
}
declare module 'intl-tel-input/src/spec/tests/methods/setCountry.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/methods/setCountry'>;
}
declare module 'intl-tel-input/src/spec/tests/methods/setNumber.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/methods/setNumber'>;
}
declare module 'intl-tel-input/src/spec/tests/options/allowDropdown.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/options/allowDropdown'>;
}
declare module 'intl-tel-input/src/spec/tests/options/autoHideDialCode.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/options/autoHideDialCode'>;
}
declare module 'intl-tel-input/src/spec/tests/options/autoPlaceholder.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/options/autoPlaceholder'>;
}
declare module 'intl-tel-input/src/spec/tests/options/customPlaceholder.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/options/customPlaceholder'>;
}
declare module 'intl-tel-input/src/spec/tests/options/dropdownContainer.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/options/dropdownContainer'>;
}
declare module 'intl-tel-input/src/spec/tests/options/excludeCountries.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/options/excludeCountries'>;
}
declare module 'intl-tel-input/src/spec/tests/options/formatOnInit.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/options/formatOnInit'>;
}
declare module 'intl-tel-input/src/spec/tests/options/geoIpLookup.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/options/geoIpLookup'>;
}
declare module 'intl-tel-input/src/spec/tests/options/initialCountry.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/options/initialCountry'>;
}
declare module 'intl-tel-input/src/spec/tests/options/nationalMode.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/options/nationalMode'>;
}
declare module 'intl-tel-input/src/spec/tests/options/numberType.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/options/numberType'>;
}
declare module 'intl-tel-input/src/spec/tests/options/onlyCountries.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/options/onlyCountries'>;
}
declare module 'intl-tel-input/src/spec/tests/options/preferredCountries.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/options/preferredCountries'>;
}
declare module 'intl-tel-input/src/spec/tests/options/separateDialCode.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/options/separateDialCode'>;
}
declare module 'intl-tel-input/src/spec/tests/options/utilsScript.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/options/utilsScript'>;
}
declare module 'intl-tel-input/src/spec/tests/static/defaults.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/static/defaults'>;
}
declare module 'intl-tel-input/src/spec/tests/static/getCountryData.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/static/getCountryData'>;
}
declare module 'intl-tel-input/src/spec/tests/static/loadUtils.js' {
  declare module.exports: $Exports<'intl-tel-input/src/spec/tests/static/loadUtils'>;
}
