// flow-typed signature: 39b5fd84603089756429b97275261c0c
// flow-typed version: <<STUB>>/normalize.css_v^3.0.3/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
