// flow-typed signature: 29cf96837618481a0624f588e369d479
// flow-typed version: <<STUB>>/postcss-cli_v^5.0.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-cli/lib/args' {
  declare module.exports: any;
}

declare module 'postcss-cli/lib/depGraph' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-cli/index' {
  declare module.exports: $Exports<'postcss-cli'>;
}
declare module 'postcss-cli/index.js' {
  declare module.exports: $Exports<'postcss-cli'>;
}
declare module 'postcss-cli/lib/args.js' {
  declare module.exports: $Exports<'postcss-cli/lib/args'>;
}
declare module 'postcss-cli/lib/depGraph.js' {
  declare module.exports: $Exports<'postcss-cli/lib/depGraph'>;
}
