// flow-typed signature: 6f0f2c4f89ffe30339d398a55794df26
// flow-typed version: <<STUB>>/stylelint_v^4.3.3/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint/dist/buildConfig' {
  declare module.exports: any;
}

declare module 'stylelint/dist/cli' {
  declare module.exports: any;
}

declare module 'stylelint/dist/createPlugin' {
  declare module.exports: any;
}

declare module 'stylelint/dist/disableRanges' {
  declare module.exports: any;
}

declare module 'stylelint/dist/formatters/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/formatters/jsonFormatter' {
  declare module.exports: any;
}

declare module 'stylelint/dist/formatters/stringFormatter' {
  declare module.exports: any;
}

declare module 'stylelint/dist/formatters/verboseFormatter' {
  declare module.exports: any;
}

declare module 'stylelint/dist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/normalizeRuleSettings' {
  declare module.exports: any;
}

declare module 'stylelint/dist/postcssPlugin' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/at-rule-empty-line-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/at-rule-no-vendor-prefix/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/block-closing-brace-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/block-closing-brace-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/block-closing-brace-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/block-closing-brace-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/block-no-empty/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/block-no-single-line/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/block-opening-brace-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/block-opening-brace-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/block-opening-brace-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/block-opening-brace-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/color-hex-case/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/color-hex-length/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/color-named/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/color-named/representations' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/color-no-hex/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/color-no-indistinguishable/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/color-no-invalid-hex/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/color-no-named/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/comment-empty-line-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/comment-whitespace-inside/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/custom-media-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/custom-property-no-outside-root/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/custom-property-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-bang-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-bang-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-block-no-duplicate-properties/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-block-no-shorthand-property-overrides/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-block-no-shorthand-property-overrides/shorthands' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-block-no-single-line/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-block-properties-order/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-block-semicolon-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-block-semicolon-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-block-semicolon-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-block-semicolon-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-block-single-line-max-declarations/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-block-trailing-semicolon/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-colon-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-colon-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-colon-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/declaration-no-important/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/font-family-name-quotes/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/font-weight-notation/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-blacklist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-calc-no-unspaced-operator/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-comma-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-comma-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-comma-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-comma-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-linear-gradient-no-nonstandard-direction/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-parentheses-newline-inside/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-parentheses-space-inside/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-url-quotes/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-whitelist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/function-whitespace-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/indentation/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/max-empty-lines/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/max-line-length/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/max-nesting-depth/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-feature-colon-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-feature-colon-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-feature-name-no-vendor-prefix/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-feature-no-missing-punctuation/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-feature-range-operator-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-feature-range-operator-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-query-list-comma-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-query-list-comma-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-query-list-comma-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-query-list-comma-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/media-query-parentheses-space-inside/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/no-browser-hacks/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/no-descending-specificity/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/no-duplicate-selectors/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/no-eol-whitespace/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/no-indistinguishable-colors/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/no-invalid-double-slash-comments/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/no-missing-eof-newline/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/no-unknown-animations/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/no-unsupported-browser-features/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/number-leading-zero/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/number-max-precision/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/number-no-trailing-zeros/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/number-zero-length-no-unit/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/property-blacklist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/property-no-vendor-prefix/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/property-unit-blacklist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/property-unit-whitelist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/property-value-blacklist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/property-value-whitelist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/property-whitelist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/root-no-standard-properties/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/rule-nested-empty-line-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/rule-no-duplicate-properties/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/rule-no-shorthand-property-overrides/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/rule-no-shorthand-property-overrides/shorthands' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/rule-non-nested-empty-line-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/rule-properties-order/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/rule-trailing-semicolon/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-class-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-combinator-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-combinator-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-id-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-list-comma-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-list-comma-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-list-comma-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-list-comma-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-max-specificity/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-no-attribute/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-no-combinator/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-no-descending-specificity/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-no-id/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-no-type/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-no-universal/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-no-vendor-prefix/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-pseudo-element-colon-notation/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/selector-root-no-composition/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/string-no-newline/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/string-quotes/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/time-no-imperceptible/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/unit-blacklist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/unit-whitelist/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/value-list-comma-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/value-list-comma-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/value-list-comma-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/value-list-comma-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/rules/value-no-vendor-prefix/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/standalone' {
  declare module.exports: any;
}

declare module 'stylelint/dist/testUtils/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/testUtils/ruleTester' {
  declare module.exports: any;
}

declare module 'stylelint/dist/testUtils/warningFreeBasics' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/blurComments' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/blurFunctionArguments' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/configurationError' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/cssDeclarationIsMap' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/cssFunctionArguments' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/cssNodeContextLookup' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/cssPropertyIsVariable' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/cssRuleHasSelectorEndingWithColon' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/cssStatementBlockString' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/cssStatementHasBlock' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/cssStatementHasEmptyBlock' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/cssStatementStringBeforeBlock' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/cssWordIsVariable' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/declarationValueIndexOffset' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/findMediaContext' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/index' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isAutoprefixable' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isLowerSpecificity' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isSingleLineString' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isValidHex' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/isWhitespace' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/matchesStringOrRegExp' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/mediaQueryParamIndexOffset' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/optionsHaveException' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/optionsHaveIgnored' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/rawNodeString' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/report' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/ruleMessages' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/styleSearch' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/validateOptions' {
  declare module.exports: any;
}

declare module 'stylelint/dist/utils/whitespaceChecker' {
  declare module.exports: any;
}

declare module 'stylelint/src/buildConfig' {
  declare module.exports: any;
}

declare module 'stylelint/src/cli' {
  declare module.exports: any;
}

declare module 'stylelint/src/createPlugin' {
  declare module.exports: any;
}

declare module 'stylelint/src/disableRanges' {
  declare module.exports: any;
}

declare module 'stylelint/src/formatters/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/formatters/jsonFormatter' {
  declare module.exports: any;
}

declare module 'stylelint/src/formatters/stringFormatter' {
  declare module.exports: any;
}

declare module 'stylelint/src/formatters/verboseFormatter' {
  declare module.exports: any;
}

declare module 'stylelint/src/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/normalizeRuleSettings' {
  declare module.exports: any;
}

declare module 'stylelint/src/postcssPlugin' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/at-rule-empty-line-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/at-rule-no-vendor-prefix/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/block-closing-brace-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/block-closing-brace-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/block-closing-brace-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/block-closing-brace-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/block-no-empty/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/block-no-single-line/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/block-opening-brace-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/block-opening-brace-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/block-opening-brace-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/block-opening-brace-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/color-hex-case/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/color-hex-length/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/color-named/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/color-named/representations' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/color-no-hex/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/color-no-invalid-hex/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/color-no-named/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/comment-empty-line-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/comment-whitespace-inside/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/custom-media-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/custom-property-no-outside-root/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/custom-property-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/declaration-bang-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/declaration-bang-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/declaration-block-no-duplicate-properties/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/declaration-block-no-shorthand-property-overrides/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/declaration-block-no-shorthand-property-overrides/shorthands' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/declaration-block-no-single-line/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/declaration-block-properties-order/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/declaration-block-semicolon-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/declaration-block-semicolon-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/declaration-block-semicolon-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/declaration-block-semicolon-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/declaration-block-single-line-max-declarations/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/declaration-block-trailing-semicolon/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/declaration-colon-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/declaration-colon-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/declaration-colon-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/declaration-no-important/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/font-family-name-quotes/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/font-weight-notation/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/function-blacklist/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/function-calc-no-unspaced-operator/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/function-comma-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/function-comma-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/function-comma-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/function-comma-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/function-linear-gradient-no-nonstandard-direction/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/function-parentheses-newline-inside/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/function-parentheses-space-inside/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/function-url-quotes/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/function-whitelist/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/function-whitespace-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/indentation/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/max-empty-lines/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/max-line-length/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/max-nesting-depth/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/media-feature-colon-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/media-feature-colon-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/media-feature-name-no-vendor-prefix/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/media-feature-no-missing-punctuation/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/media-feature-range-operator-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/media-feature-range-operator-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/media-query-list-comma-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/media-query-list-comma-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/media-query-list-comma-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/media-query-list-comma-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/media-query-parentheses-space-inside/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/no-browser-hacks/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/no-descending-specificity/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/no-duplicate-selectors/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/no-eol-whitespace/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/no-indistinguishable-colors/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/no-invalid-double-slash-comments/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/no-missing-eof-newline/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/no-unknown-animations/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/no-unsupported-browser-features/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/number-leading-zero/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/number-max-precision/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/number-no-trailing-zeros/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/number-zero-length-no-unit/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/property-blacklist/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/property-no-vendor-prefix/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/property-unit-blacklist/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/property-unit-whitelist/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/property-value-blacklist/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/property-value-whitelist/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/property-whitelist/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/root-no-standard-properties/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/rule-nested-empty-line-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/rule-no-duplicate-properties/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/rule-no-shorthand-property-overrides/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/rule-no-shorthand-property-overrides/shorthands' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/rule-non-nested-empty-line-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/rule-properties-order/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/rule-trailing-semicolon/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/selector-class-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/selector-combinator-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/selector-combinator-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/selector-id-pattern/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/selector-list-comma-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/selector-list-comma-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/selector-list-comma-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/selector-list-comma-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/selector-max-specificity/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/selector-no-attribute/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/selector-no-combinator/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/selector-no-id/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/selector-no-type/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/selector-no-universal/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/selector-no-vendor-prefix/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/selector-pseudo-element-colon-notation/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/selector-root-no-composition/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/string-no-newline/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/string-quotes/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/time-no-imperceptible/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/unit-blacklist/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/unit-whitelist/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/value-list-comma-newline-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/value-list-comma-newline-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/value-list-comma-space-after/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/value-list-comma-space-before/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/rules/value-no-vendor-prefix/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/standalone' {
  declare module.exports: any;
}

declare module 'stylelint/src/testUtils/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/testUtils/ruleTester' {
  declare module.exports: any;
}

declare module 'stylelint/src/testUtils/warningFreeBasics' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/blurComments' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/blurFunctionArguments' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/configurationError' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/cssDeclarationIsMap' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/cssFunctionArguments' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/cssNodeContextLookup' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/cssRuleHasSelectorEndingWithColon' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/cssStatementBlockString' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/cssStatementHasBlock' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/cssStatementHasEmptyBlock' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/cssStatementStringBeforeBlock' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/cssWordIsVariable' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/declarationValueIndexOffset' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/findMediaContext' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/index' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/isAutoprefixable' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/isLowerSpecificity' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/isSingleLineString' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/isValidHex' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/isWhitespace' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/matchesStringOrRegExp' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/mediaQueryParamIndexOffset' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/optionsHaveException' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/optionsHaveIgnored' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/rawNodeString' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/report' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/ruleMessages' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/styleSearch' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/validateOptions' {
  declare module.exports: any;
}

declare module 'stylelint/src/utils/whitespaceChecker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint/dist/buildConfig.js' {
  declare module.exports: $Exports<'stylelint/dist/buildConfig'>;
}
declare module 'stylelint/dist/cli.js' {
  declare module.exports: $Exports<'stylelint/dist/cli'>;
}
declare module 'stylelint/dist/createPlugin.js' {
  declare module.exports: $Exports<'stylelint/dist/createPlugin'>;
}
declare module 'stylelint/dist/disableRanges.js' {
  declare module.exports: $Exports<'stylelint/dist/disableRanges'>;
}
declare module 'stylelint/dist/formatters/index.js' {
  declare module.exports: $Exports<'stylelint/dist/formatters/index'>;
}
declare module 'stylelint/dist/formatters/jsonFormatter.js' {
  declare module.exports: $Exports<'stylelint/dist/formatters/jsonFormatter'>;
}
declare module 'stylelint/dist/formatters/stringFormatter.js' {
  declare module.exports: $Exports<'stylelint/dist/formatters/stringFormatter'>;
}
declare module 'stylelint/dist/formatters/verboseFormatter.js' {
  declare module.exports: $Exports<'stylelint/dist/formatters/verboseFormatter'>;
}
declare module 'stylelint/dist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/index'>;
}
declare module 'stylelint/dist/normalizeRuleSettings.js' {
  declare module.exports: $Exports<'stylelint/dist/normalizeRuleSettings'>;
}
declare module 'stylelint/dist/postcssPlugin.js' {
  declare module.exports: $Exports<'stylelint/dist/postcssPlugin'>;
}
declare module 'stylelint/dist/rules/at-rule-empty-line-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/at-rule-empty-line-before/index'>;
}
declare module 'stylelint/dist/rules/at-rule-no-vendor-prefix/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/at-rule-no-vendor-prefix/index'>;
}
declare module 'stylelint/dist/rules/block-closing-brace-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/block-closing-brace-newline-after/index'>;
}
declare module 'stylelint/dist/rules/block-closing-brace-newline-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/block-closing-brace-newline-before/index'>;
}
declare module 'stylelint/dist/rules/block-closing-brace-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/block-closing-brace-space-after/index'>;
}
declare module 'stylelint/dist/rules/block-closing-brace-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/block-closing-brace-space-before/index'>;
}
declare module 'stylelint/dist/rules/block-no-empty/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/block-no-empty/index'>;
}
declare module 'stylelint/dist/rules/block-no-single-line/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/block-no-single-line/index'>;
}
declare module 'stylelint/dist/rules/block-opening-brace-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/block-opening-brace-newline-after/index'>;
}
declare module 'stylelint/dist/rules/block-opening-brace-newline-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/block-opening-brace-newline-before/index'>;
}
declare module 'stylelint/dist/rules/block-opening-brace-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/block-opening-brace-space-after/index'>;
}
declare module 'stylelint/dist/rules/block-opening-brace-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/block-opening-brace-space-before/index'>;
}
declare module 'stylelint/dist/rules/color-hex-case/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/color-hex-case/index'>;
}
declare module 'stylelint/dist/rules/color-hex-length/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/color-hex-length/index'>;
}
declare module 'stylelint/dist/rules/color-named/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/color-named/index'>;
}
declare module 'stylelint/dist/rules/color-named/representations.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/color-named/representations'>;
}
declare module 'stylelint/dist/rules/color-no-hex/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/color-no-hex/index'>;
}
declare module 'stylelint/dist/rules/color-no-indistinguishable/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/color-no-indistinguishable/index'>;
}
declare module 'stylelint/dist/rules/color-no-invalid-hex/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/color-no-invalid-hex/index'>;
}
declare module 'stylelint/dist/rules/color-no-named/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/color-no-named/index'>;
}
declare module 'stylelint/dist/rules/comment-empty-line-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/comment-empty-line-before/index'>;
}
declare module 'stylelint/dist/rules/comment-whitespace-inside/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/comment-whitespace-inside/index'>;
}
declare module 'stylelint/dist/rules/custom-media-pattern/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/custom-media-pattern/index'>;
}
declare module 'stylelint/dist/rules/custom-property-no-outside-root/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/custom-property-no-outside-root/index'>;
}
declare module 'stylelint/dist/rules/custom-property-pattern/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/custom-property-pattern/index'>;
}
declare module 'stylelint/dist/rules/declaration-bang-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-bang-space-after/index'>;
}
declare module 'stylelint/dist/rules/declaration-bang-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-bang-space-before/index'>;
}
declare module 'stylelint/dist/rules/declaration-block-no-duplicate-properties/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-block-no-duplicate-properties/index'>;
}
declare module 'stylelint/dist/rules/declaration-block-no-shorthand-property-overrides/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-block-no-shorthand-property-overrides/index'>;
}
declare module 'stylelint/dist/rules/declaration-block-no-shorthand-property-overrides/shorthands.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-block-no-shorthand-property-overrides/shorthands'>;
}
declare module 'stylelint/dist/rules/declaration-block-no-single-line/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-block-no-single-line/index'>;
}
declare module 'stylelint/dist/rules/declaration-block-properties-order/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-block-properties-order/index'>;
}
declare module 'stylelint/dist/rules/declaration-block-semicolon-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-block-semicolon-newline-after/index'>;
}
declare module 'stylelint/dist/rules/declaration-block-semicolon-newline-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-block-semicolon-newline-before/index'>;
}
declare module 'stylelint/dist/rules/declaration-block-semicolon-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-block-semicolon-space-after/index'>;
}
declare module 'stylelint/dist/rules/declaration-block-semicolon-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-block-semicolon-space-before/index'>;
}
declare module 'stylelint/dist/rules/declaration-block-single-line-max-declarations/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-block-single-line-max-declarations/index'>;
}
declare module 'stylelint/dist/rules/declaration-block-trailing-semicolon/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-block-trailing-semicolon/index'>;
}
declare module 'stylelint/dist/rules/declaration-colon-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-colon-newline-after/index'>;
}
declare module 'stylelint/dist/rules/declaration-colon-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-colon-space-after/index'>;
}
declare module 'stylelint/dist/rules/declaration-colon-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-colon-space-before/index'>;
}
declare module 'stylelint/dist/rules/declaration-no-important/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/declaration-no-important/index'>;
}
declare module 'stylelint/dist/rules/font-family-name-quotes/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/font-family-name-quotes/index'>;
}
declare module 'stylelint/dist/rules/font-weight-notation/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/font-weight-notation/index'>;
}
declare module 'stylelint/dist/rules/function-blacklist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-blacklist/index'>;
}
declare module 'stylelint/dist/rules/function-calc-no-unspaced-operator/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-calc-no-unspaced-operator/index'>;
}
declare module 'stylelint/dist/rules/function-comma-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-comma-newline-after/index'>;
}
declare module 'stylelint/dist/rules/function-comma-newline-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-comma-newline-before/index'>;
}
declare module 'stylelint/dist/rules/function-comma-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-comma-space-after/index'>;
}
declare module 'stylelint/dist/rules/function-comma-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-comma-space-before/index'>;
}
declare module 'stylelint/dist/rules/function-linear-gradient-no-nonstandard-direction/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-linear-gradient-no-nonstandard-direction/index'>;
}
declare module 'stylelint/dist/rules/function-parentheses-newline-inside/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-parentheses-newline-inside/index'>;
}
declare module 'stylelint/dist/rules/function-parentheses-space-inside/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-parentheses-space-inside/index'>;
}
declare module 'stylelint/dist/rules/function-url-quotes/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-url-quotes/index'>;
}
declare module 'stylelint/dist/rules/function-whitelist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-whitelist/index'>;
}
declare module 'stylelint/dist/rules/function-whitespace-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/function-whitespace-after/index'>;
}
declare module 'stylelint/dist/rules/indentation/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/indentation/index'>;
}
declare module 'stylelint/dist/rules/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/index'>;
}
declare module 'stylelint/dist/rules/max-empty-lines/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/max-empty-lines/index'>;
}
declare module 'stylelint/dist/rules/max-line-length/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/max-line-length/index'>;
}
declare module 'stylelint/dist/rules/max-nesting-depth/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/max-nesting-depth/index'>;
}
declare module 'stylelint/dist/rules/media-feature-colon-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-feature-colon-space-after/index'>;
}
declare module 'stylelint/dist/rules/media-feature-colon-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-feature-colon-space-before/index'>;
}
declare module 'stylelint/dist/rules/media-feature-name-no-vendor-prefix/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-feature-name-no-vendor-prefix/index'>;
}
declare module 'stylelint/dist/rules/media-feature-no-missing-punctuation/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-feature-no-missing-punctuation/index'>;
}
declare module 'stylelint/dist/rules/media-feature-range-operator-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-feature-range-operator-space-after/index'>;
}
declare module 'stylelint/dist/rules/media-feature-range-operator-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-feature-range-operator-space-before/index'>;
}
declare module 'stylelint/dist/rules/media-query-list-comma-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-query-list-comma-newline-after/index'>;
}
declare module 'stylelint/dist/rules/media-query-list-comma-newline-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-query-list-comma-newline-before/index'>;
}
declare module 'stylelint/dist/rules/media-query-list-comma-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-query-list-comma-space-after/index'>;
}
declare module 'stylelint/dist/rules/media-query-list-comma-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-query-list-comma-space-before/index'>;
}
declare module 'stylelint/dist/rules/media-query-parentheses-space-inside/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/media-query-parentheses-space-inside/index'>;
}
declare module 'stylelint/dist/rules/no-browser-hacks/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/no-browser-hacks/index'>;
}
declare module 'stylelint/dist/rules/no-descending-specificity/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/no-descending-specificity/index'>;
}
declare module 'stylelint/dist/rules/no-duplicate-selectors/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/no-duplicate-selectors/index'>;
}
declare module 'stylelint/dist/rules/no-eol-whitespace/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/no-eol-whitespace/index'>;
}
declare module 'stylelint/dist/rules/no-indistinguishable-colors/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/no-indistinguishable-colors/index'>;
}
declare module 'stylelint/dist/rules/no-invalid-double-slash-comments/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/no-invalid-double-slash-comments/index'>;
}
declare module 'stylelint/dist/rules/no-missing-eof-newline/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/no-missing-eof-newline/index'>;
}
declare module 'stylelint/dist/rules/no-unknown-animations/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/no-unknown-animations/index'>;
}
declare module 'stylelint/dist/rules/no-unsupported-browser-features/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/no-unsupported-browser-features/index'>;
}
declare module 'stylelint/dist/rules/number-leading-zero/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/number-leading-zero/index'>;
}
declare module 'stylelint/dist/rules/number-max-precision/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/number-max-precision/index'>;
}
declare module 'stylelint/dist/rules/number-no-trailing-zeros/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/number-no-trailing-zeros/index'>;
}
declare module 'stylelint/dist/rules/number-zero-length-no-unit/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/number-zero-length-no-unit/index'>;
}
declare module 'stylelint/dist/rules/property-blacklist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/property-blacklist/index'>;
}
declare module 'stylelint/dist/rules/property-no-vendor-prefix/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/property-no-vendor-prefix/index'>;
}
declare module 'stylelint/dist/rules/property-unit-blacklist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/property-unit-blacklist/index'>;
}
declare module 'stylelint/dist/rules/property-unit-whitelist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/property-unit-whitelist/index'>;
}
declare module 'stylelint/dist/rules/property-value-blacklist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/property-value-blacklist/index'>;
}
declare module 'stylelint/dist/rules/property-value-whitelist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/property-value-whitelist/index'>;
}
declare module 'stylelint/dist/rules/property-whitelist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/property-whitelist/index'>;
}
declare module 'stylelint/dist/rules/root-no-standard-properties/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/root-no-standard-properties/index'>;
}
declare module 'stylelint/dist/rules/rule-nested-empty-line-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/rule-nested-empty-line-before/index'>;
}
declare module 'stylelint/dist/rules/rule-no-duplicate-properties/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/rule-no-duplicate-properties/index'>;
}
declare module 'stylelint/dist/rules/rule-no-shorthand-property-overrides/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/rule-no-shorthand-property-overrides/index'>;
}
declare module 'stylelint/dist/rules/rule-no-shorthand-property-overrides/shorthands.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/rule-no-shorthand-property-overrides/shorthands'>;
}
declare module 'stylelint/dist/rules/rule-non-nested-empty-line-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/rule-non-nested-empty-line-before/index'>;
}
declare module 'stylelint/dist/rules/rule-properties-order/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/rule-properties-order/index'>;
}
declare module 'stylelint/dist/rules/rule-trailing-semicolon/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/rule-trailing-semicolon/index'>;
}
declare module 'stylelint/dist/rules/selector-class-pattern/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-class-pattern/index'>;
}
declare module 'stylelint/dist/rules/selector-combinator-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-combinator-space-after/index'>;
}
declare module 'stylelint/dist/rules/selector-combinator-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-combinator-space-before/index'>;
}
declare module 'stylelint/dist/rules/selector-id-pattern/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-id-pattern/index'>;
}
declare module 'stylelint/dist/rules/selector-list-comma-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-list-comma-newline-after/index'>;
}
declare module 'stylelint/dist/rules/selector-list-comma-newline-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-list-comma-newline-before/index'>;
}
declare module 'stylelint/dist/rules/selector-list-comma-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-list-comma-space-after/index'>;
}
declare module 'stylelint/dist/rules/selector-list-comma-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-list-comma-space-before/index'>;
}
declare module 'stylelint/dist/rules/selector-max-specificity/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-max-specificity/index'>;
}
declare module 'stylelint/dist/rules/selector-no-attribute/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-no-attribute/index'>;
}
declare module 'stylelint/dist/rules/selector-no-combinator/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-no-combinator/index'>;
}
declare module 'stylelint/dist/rules/selector-no-descending-specificity/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-no-descending-specificity/index'>;
}
declare module 'stylelint/dist/rules/selector-no-id/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-no-id/index'>;
}
declare module 'stylelint/dist/rules/selector-no-type/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-no-type/index'>;
}
declare module 'stylelint/dist/rules/selector-no-universal/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-no-universal/index'>;
}
declare module 'stylelint/dist/rules/selector-no-vendor-prefix/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-no-vendor-prefix/index'>;
}
declare module 'stylelint/dist/rules/selector-pseudo-element-colon-notation/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-pseudo-element-colon-notation/index'>;
}
declare module 'stylelint/dist/rules/selector-root-no-composition/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/selector-root-no-composition/index'>;
}
declare module 'stylelint/dist/rules/string-no-newline/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/string-no-newline/index'>;
}
declare module 'stylelint/dist/rules/string-quotes/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/string-quotes/index'>;
}
declare module 'stylelint/dist/rules/time-no-imperceptible/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/time-no-imperceptible/index'>;
}
declare module 'stylelint/dist/rules/unit-blacklist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/unit-blacklist/index'>;
}
declare module 'stylelint/dist/rules/unit-whitelist/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/unit-whitelist/index'>;
}
declare module 'stylelint/dist/rules/value-list-comma-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/value-list-comma-newline-after/index'>;
}
declare module 'stylelint/dist/rules/value-list-comma-newline-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/value-list-comma-newline-before/index'>;
}
declare module 'stylelint/dist/rules/value-list-comma-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/value-list-comma-space-after/index'>;
}
declare module 'stylelint/dist/rules/value-list-comma-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/value-list-comma-space-before/index'>;
}
declare module 'stylelint/dist/rules/value-no-vendor-prefix/index.js' {
  declare module.exports: $Exports<'stylelint/dist/rules/value-no-vendor-prefix/index'>;
}
declare module 'stylelint/dist/standalone.js' {
  declare module.exports: $Exports<'stylelint/dist/standalone'>;
}
declare module 'stylelint/dist/testUtils/index.js' {
  declare module.exports: $Exports<'stylelint/dist/testUtils/index'>;
}
declare module 'stylelint/dist/testUtils/ruleTester.js' {
  declare module.exports: $Exports<'stylelint/dist/testUtils/ruleTester'>;
}
declare module 'stylelint/dist/testUtils/warningFreeBasics.js' {
  declare module.exports: $Exports<'stylelint/dist/testUtils/warningFreeBasics'>;
}
declare module 'stylelint/dist/utils/blurComments.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/blurComments'>;
}
declare module 'stylelint/dist/utils/blurFunctionArguments.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/blurFunctionArguments'>;
}
declare module 'stylelint/dist/utils/configurationError.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/configurationError'>;
}
declare module 'stylelint/dist/utils/cssDeclarationIsMap.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/cssDeclarationIsMap'>;
}
declare module 'stylelint/dist/utils/cssFunctionArguments.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/cssFunctionArguments'>;
}
declare module 'stylelint/dist/utils/cssNodeContextLookup.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/cssNodeContextLookup'>;
}
declare module 'stylelint/dist/utils/cssPropertyIsVariable.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/cssPropertyIsVariable'>;
}
declare module 'stylelint/dist/utils/cssRuleHasSelectorEndingWithColon.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/cssRuleHasSelectorEndingWithColon'>;
}
declare module 'stylelint/dist/utils/cssStatementBlockString.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/cssStatementBlockString'>;
}
declare module 'stylelint/dist/utils/cssStatementHasBlock.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/cssStatementHasBlock'>;
}
declare module 'stylelint/dist/utils/cssStatementHasEmptyBlock.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/cssStatementHasEmptyBlock'>;
}
declare module 'stylelint/dist/utils/cssStatementStringBeforeBlock.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/cssStatementStringBeforeBlock'>;
}
declare module 'stylelint/dist/utils/cssWordIsVariable.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/cssWordIsVariable'>;
}
declare module 'stylelint/dist/utils/declarationValueIndexOffset.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/declarationValueIndexOffset'>;
}
declare module 'stylelint/dist/utils/findMediaContext.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/findMediaContext'>;
}
declare module 'stylelint/dist/utils/index.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/index'>;
}
declare module 'stylelint/dist/utils/isAutoprefixable.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isAutoprefixable'>;
}
declare module 'stylelint/dist/utils/isLowerSpecificity.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isLowerSpecificity'>;
}
declare module 'stylelint/dist/utils/isSingleLineString.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isSingleLineString'>;
}
declare module 'stylelint/dist/utils/isValidHex.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isValidHex'>;
}
declare module 'stylelint/dist/utils/isWhitespace.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/isWhitespace'>;
}
declare module 'stylelint/dist/utils/matchesStringOrRegExp.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/matchesStringOrRegExp'>;
}
declare module 'stylelint/dist/utils/mediaQueryParamIndexOffset.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/mediaQueryParamIndexOffset'>;
}
declare module 'stylelint/dist/utils/optionsHaveException.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/optionsHaveException'>;
}
declare module 'stylelint/dist/utils/optionsHaveIgnored.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/optionsHaveIgnored'>;
}
declare module 'stylelint/dist/utils/rawNodeString.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/rawNodeString'>;
}
declare module 'stylelint/dist/utils/report.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/report'>;
}
declare module 'stylelint/dist/utils/ruleMessages.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/ruleMessages'>;
}
declare module 'stylelint/dist/utils/styleSearch.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/styleSearch'>;
}
declare module 'stylelint/dist/utils/validateOptions.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/validateOptions'>;
}
declare module 'stylelint/dist/utils/whitespaceChecker.js' {
  declare module.exports: $Exports<'stylelint/dist/utils/whitespaceChecker'>;
}
declare module 'stylelint/src/buildConfig.js' {
  declare module.exports: $Exports<'stylelint/src/buildConfig'>;
}
declare module 'stylelint/src/cli.js' {
  declare module.exports: $Exports<'stylelint/src/cli'>;
}
declare module 'stylelint/src/createPlugin.js' {
  declare module.exports: $Exports<'stylelint/src/createPlugin'>;
}
declare module 'stylelint/src/disableRanges.js' {
  declare module.exports: $Exports<'stylelint/src/disableRanges'>;
}
declare module 'stylelint/src/formatters/index.js' {
  declare module.exports: $Exports<'stylelint/src/formatters/index'>;
}
declare module 'stylelint/src/formatters/jsonFormatter.js' {
  declare module.exports: $Exports<'stylelint/src/formatters/jsonFormatter'>;
}
declare module 'stylelint/src/formatters/stringFormatter.js' {
  declare module.exports: $Exports<'stylelint/src/formatters/stringFormatter'>;
}
declare module 'stylelint/src/formatters/verboseFormatter.js' {
  declare module.exports: $Exports<'stylelint/src/formatters/verboseFormatter'>;
}
declare module 'stylelint/src/index.js' {
  declare module.exports: $Exports<'stylelint/src/index'>;
}
declare module 'stylelint/src/normalizeRuleSettings.js' {
  declare module.exports: $Exports<'stylelint/src/normalizeRuleSettings'>;
}
declare module 'stylelint/src/postcssPlugin.js' {
  declare module.exports: $Exports<'stylelint/src/postcssPlugin'>;
}
declare module 'stylelint/src/rules/at-rule-empty-line-before/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/at-rule-empty-line-before/index'>;
}
declare module 'stylelint/src/rules/at-rule-no-vendor-prefix/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/at-rule-no-vendor-prefix/index'>;
}
declare module 'stylelint/src/rules/block-closing-brace-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/block-closing-brace-newline-after/index'>;
}
declare module 'stylelint/src/rules/block-closing-brace-newline-before/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/block-closing-brace-newline-before/index'>;
}
declare module 'stylelint/src/rules/block-closing-brace-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/block-closing-brace-space-after/index'>;
}
declare module 'stylelint/src/rules/block-closing-brace-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/block-closing-brace-space-before/index'>;
}
declare module 'stylelint/src/rules/block-no-empty/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/block-no-empty/index'>;
}
declare module 'stylelint/src/rules/block-no-single-line/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/block-no-single-line/index'>;
}
declare module 'stylelint/src/rules/block-opening-brace-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/block-opening-brace-newline-after/index'>;
}
declare module 'stylelint/src/rules/block-opening-brace-newline-before/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/block-opening-brace-newline-before/index'>;
}
declare module 'stylelint/src/rules/block-opening-brace-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/block-opening-brace-space-after/index'>;
}
declare module 'stylelint/src/rules/block-opening-brace-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/block-opening-brace-space-before/index'>;
}
declare module 'stylelint/src/rules/color-hex-case/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/color-hex-case/index'>;
}
declare module 'stylelint/src/rules/color-hex-length/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/color-hex-length/index'>;
}
declare module 'stylelint/src/rules/color-named/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/color-named/index'>;
}
declare module 'stylelint/src/rules/color-named/representations.js' {
  declare module.exports: $Exports<'stylelint/src/rules/color-named/representations'>;
}
declare module 'stylelint/src/rules/color-no-hex/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/color-no-hex/index'>;
}
declare module 'stylelint/src/rules/color-no-invalid-hex/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/color-no-invalid-hex/index'>;
}
declare module 'stylelint/src/rules/color-no-named/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/color-no-named/index'>;
}
declare module 'stylelint/src/rules/comment-empty-line-before/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/comment-empty-line-before/index'>;
}
declare module 'stylelint/src/rules/comment-whitespace-inside/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/comment-whitespace-inside/index'>;
}
declare module 'stylelint/src/rules/custom-media-pattern/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/custom-media-pattern/index'>;
}
declare module 'stylelint/src/rules/custom-property-no-outside-root/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/custom-property-no-outside-root/index'>;
}
declare module 'stylelint/src/rules/custom-property-pattern/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/custom-property-pattern/index'>;
}
declare module 'stylelint/src/rules/declaration-bang-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/declaration-bang-space-after/index'>;
}
declare module 'stylelint/src/rules/declaration-bang-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/declaration-bang-space-before/index'>;
}
declare module 'stylelint/src/rules/declaration-block-no-duplicate-properties/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/declaration-block-no-duplicate-properties/index'>;
}
declare module 'stylelint/src/rules/declaration-block-no-shorthand-property-overrides/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/declaration-block-no-shorthand-property-overrides/index'>;
}
declare module 'stylelint/src/rules/declaration-block-no-shorthand-property-overrides/shorthands.js' {
  declare module.exports: $Exports<'stylelint/src/rules/declaration-block-no-shorthand-property-overrides/shorthands'>;
}
declare module 'stylelint/src/rules/declaration-block-no-single-line/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/declaration-block-no-single-line/index'>;
}
declare module 'stylelint/src/rules/declaration-block-properties-order/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/declaration-block-properties-order/index'>;
}
declare module 'stylelint/src/rules/declaration-block-semicolon-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/declaration-block-semicolon-newline-after/index'>;
}
declare module 'stylelint/src/rules/declaration-block-semicolon-newline-before/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/declaration-block-semicolon-newline-before/index'>;
}
declare module 'stylelint/src/rules/declaration-block-semicolon-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/declaration-block-semicolon-space-after/index'>;
}
declare module 'stylelint/src/rules/declaration-block-semicolon-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/declaration-block-semicolon-space-before/index'>;
}
declare module 'stylelint/src/rules/declaration-block-single-line-max-declarations/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/declaration-block-single-line-max-declarations/index'>;
}
declare module 'stylelint/src/rules/declaration-block-trailing-semicolon/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/declaration-block-trailing-semicolon/index'>;
}
declare module 'stylelint/src/rules/declaration-colon-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/declaration-colon-newline-after/index'>;
}
declare module 'stylelint/src/rules/declaration-colon-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/declaration-colon-space-after/index'>;
}
declare module 'stylelint/src/rules/declaration-colon-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/declaration-colon-space-before/index'>;
}
declare module 'stylelint/src/rules/declaration-no-important/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/declaration-no-important/index'>;
}
declare module 'stylelint/src/rules/font-family-name-quotes/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/font-family-name-quotes/index'>;
}
declare module 'stylelint/src/rules/font-weight-notation/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/font-weight-notation/index'>;
}
declare module 'stylelint/src/rules/function-blacklist/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/function-blacklist/index'>;
}
declare module 'stylelint/src/rules/function-calc-no-unspaced-operator/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/function-calc-no-unspaced-operator/index'>;
}
declare module 'stylelint/src/rules/function-comma-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/function-comma-newline-after/index'>;
}
declare module 'stylelint/src/rules/function-comma-newline-before/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/function-comma-newline-before/index'>;
}
declare module 'stylelint/src/rules/function-comma-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/function-comma-space-after/index'>;
}
declare module 'stylelint/src/rules/function-comma-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/function-comma-space-before/index'>;
}
declare module 'stylelint/src/rules/function-linear-gradient-no-nonstandard-direction/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/function-linear-gradient-no-nonstandard-direction/index'>;
}
declare module 'stylelint/src/rules/function-parentheses-newline-inside/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/function-parentheses-newline-inside/index'>;
}
declare module 'stylelint/src/rules/function-parentheses-space-inside/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/function-parentheses-space-inside/index'>;
}
declare module 'stylelint/src/rules/function-url-quotes/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/function-url-quotes/index'>;
}
declare module 'stylelint/src/rules/function-whitelist/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/function-whitelist/index'>;
}
declare module 'stylelint/src/rules/function-whitespace-after/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/function-whitespace-after/index'>;
}
declare module 'stylelint/src/rules/indentation/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/indentation/index'>;
}
declare module 'stylelint/src/rules/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/index'>;
}
declare module 'stylelint/src/rules/max-empty-lines/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/max-empty-lines/index'>;
}
declare module 'stylelint/src/rules/max-line-length/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/max-line-length/index'>;
}
declare module 'stylelint/src/rules/max-nesting-depth/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/max-nesting-depth/index'>;
}
declare module 'stylelint/src/rules/media-feature-colon-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/media-feature-colon-space-after/index'>;
}
declare module 'stylelint/src/rules/media-feature-colon-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/media-feature-colon-space-before/index'>;
}
declare module 'stylelint/src/rules/media-feature-name-no-vendor-prefix/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/media-feature-name-no-vendor-prefix/index'>;
}
declare module 'stylelint/src/rules/media-feature-no-missing-punctuation/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/media-feature-no-missing-punctuation/index'>;
}
declare module 'stylelint/src/rules/media-feature-range-operator-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/media-feature-range-operator-space-after/index'>;
}
declare module 'stylelint/src/rules/media-feature-range-operator-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/media-feature-range-operator-space-before/index'>;
}
declare module 'stylelint/src/rules/media-query-list-comma-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/media-query-list-comma-newline-after/index'>;
}
declare module 'stylelint/src/rules/media-query-list-comma-newline-before/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/media-query-list-comma-newline-before/index'>;
}
declare module 'stylelint/src/rules/media-query-list-comma-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/media-query-list-comma-space-after/index'>;
}
declare module 'stylelint/src/rules/media-query-list-comma-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/media-query-list-comma-space-before/index'>;
}
declare module 'stylelint/src/rules/media-query-parentheses-space-inside/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/media-query-parentheses-space-inside/index'>;
}
declare module 'stylelint/src/rules/no-browser-hacks/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/no-browser-hacks/index'>;
}
declare module 'stylelint/src/rules/no-descending-specificity/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/no-descending-specificity/index'>;
}
declare module 'stylelint/src/rules/no-duplicate-selectors/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/no-duplicate-selectors/index'>;
}
declare module 'stylelint/src/rules/no-eol-whitespace/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/no-eol-whitespace/index'>;
}
declare module 'stylelint/src/rules/no-indistinguishable-colors/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/no-indistinguishable-colors/index'>;
}
declare module 'stylelint/src/rules/no-invalid-double-slash-comments/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/no-invalid-double-slash-comments/index'>;
}
declare module 'stylelint/src/rules/no-missing-eof-newline/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/no-missing-eof-newline/index'>;
}
declare module 'stylelint/src/rules/no-unknown-animations/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/no-unknown-animations/index'>;
}
declare module 'stylelint/src/rules/no-unsupported-browser-features/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/no-unsupported-browser-features/index'>;
}
declare module 'stylelint/src/rules/number-leading-zero/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/number-leading-zero/index'>;
}
declare module 'stylelint/src/rules/number-max-precision/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/number-max-precision/index'>;
}
declare module 'stylelint/src/rules/number-no-trailing-zeros/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/number-no-trailing-zeros/index'>;
}
declare module 'stylelint/src/rules/number-zero-length-no-unit/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/number-zero-length-no-unit/index'>;
}
declare module 'stylelint/src/rules/property-blacklist/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/property-blacklist/index'>;
}
declare module 'stylelint/src/rules/property-no-vendor-prefix/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/property-no-vendor-prefix/index'>;
}
declare module 'stylelint/src/rules/property-unit-blacklist/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/property-unit-blacklist/index'>;
}
declare module 'stylelint/src/rules/property-unit-whitelist/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/property-unit-whitelist/index'>;
}
declare module 'stylelint/src/rules/property-value-blacklist/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/property-value-blacklist/index'>;
}
declare module 'stylelint/src/rules/property-value-whitelist/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/property-value-whitelist/index'>;
}
declare module 'stylelint/src/rules/property-whitelist/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/property-whitelist/index'>;
}
declare module 'stylelint/src/rules/root-no-standard-properties/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/root-no-standard-properties/index'>;
}
declare module 'stylelint/src/rules/rule-nested-empty-line-before/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/rule-nested-empty-line-before/index'>;
}
declare module 'stylelint/src/rules/rule-no-duplicate-properties/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/rule-no-duplicate-properties/index'>;
}
declare module 'stylelint/src/rules/rule-no-shorthand-property-overrides/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/rule-no-shorthand-property-overrides/index'>;
}
declare module 'stylelint/src/rules/rule-no-shorthand-property-overrides/shorthands.js' {
  declare module.exports: $Exports<'stylelint/src/rules/rule-no-shorthand-property-overrides/shorthands'>;
}
declare module 'stylelint/src/rules/rule-non-nested-empty-line-before/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/rule-non-nested-empty-line-before/index'>;
}
declare module 'stylelint/src/rules/rule-properties-order/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/rule-properties-order/index'>;
}
declare module 'stylelint/src/rules/rule-trailing-semicolon/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/rule-trailing-semicolon/index'>;
}
declare module 'stylelint/src/rules/selector-class-pattern/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/selector-class-pattern/index'>;
}
declare module 'stylelint/src/rules/selector-combinator-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/selector-combinator-space-after/index'>;
}
declare module 'stylelint/src/rules/selector-combinator-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/selector-combinator-space-before/index'>;
}
declare module 'stylelint/src/rules/selector-id-pattern/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/selector-id-pattern/index'>;
}
declare module 'stylelint/src/rules/selector-list-comma-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/selector-list-comma-newline-after/index'>;
}
declare module 'stylelint/src/rules/selector-list-comma-newline-before/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/selector-list-comma-newline-before/index'>;
}
declare module 'stylelint/src/rules/selector-list-comma-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/selector-list-comma-space-after/index'>;
}
declare module 'stylelint/src/rules/selector-list-comma-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/selector-list-comma-space-before/index'>;
}
declare module 'stylelint/src/rules/selector-max-specificity/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/selector-max-specificity/index'>;
}
declare module 'stylelint/src/rules/selector-no-attribute/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/selector-no-attribute/index'>;
}
declare module 'stylelint/src/rules/selector-no-combinator/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/selector-no-combinator/index'>;
}
declare module 'stylelint/src/rules/selector-no-id/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/selector-no-id/index'>;
}
declare module 'stylelint/src/rules/selector-no-type/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/selector-no-type/index'>;
}
declare module 'stylelint/src/rules/selector-no-universal/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/selector-no-universal/index'>;
}
declare module 'stylelint/src/rules/selector-no-vendor-prefix/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/selector-no-vendor-prefix/index'>;
}
declare module 'stylelint/src/rules/selector-pseudo-element-colon-notation/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/selector-pseudo-element-colon-notation/index'>;
}
declare module 'stylelint/src/rules/selector-root-no-composition/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/selector-root-no-composition/index'>;
}
declare module 'stylelint/src/rules/string-no-newline/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/string-no-newline/index'>;
}
declare module 'stylelint/src/rules/string-quotes/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/string-quotes/index'>;
}
declare module 'stylelint/src/rules/time-no-imperceptible/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/time-no-imperceptible/index'>;
}
declare module 'stylelint/src/rules/unit-blacklist/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/unit-blacklist/index'>;
}
declare module 'stylelint/src/rules/unit-whitelist/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/unit-whitelist/index'>;
}
declare module 'stylelint/src/rules/value-list-comma-newline-after/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/value-list-comma-newline-after/index'>;
}
declare module 'stylelint/src/rules/value-list-comma-newline-before/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/value-list-comma-newline-before/index'>;
}
declare module 'stylelint/src/rules/value-list-comma-space-after/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/value-list-comma-space-after/index'>;
}
declare module 'stylelint/src/rules/value-list-comma-space-before/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/value-list-comma-space-before/index'>;
}
declare module 'stylelint/src/rules/value-no-vendor-prefix/index.js' {
  declare module.exports: $Exports<'stylelint/src/rules/value-no-vendor-prefix/index'>;
}
declare module 'stylelint/src/standalone.js' {
  declare module.exports: $Exports<'stylelint/src/standalone'>;
}
declare module 'stylelint/src/testUtils/index.js' {
  declare module.exports: $Exports<'stylelint/src/testUtils/index'>;
}
declare module 'stylelint/src/testUtils/ruleTester.js' {
  declare module.exports: $Exports<'stylelint/src/testUtils/ruleTester'>;
}
declare module 'stylelint/src/testUtils/warningFreeBasics.js' {
  declare module.exports: $Exports<'stylelint/src/testUtils/warningFreeBasics'>;
}
declare module 'stylelint/src/utils/blurComments.js' {
  declare module.exports: $Exports<'stylelint/src/utils/blurComments'>;
}
declare module 'stylelint/src/utils/blurFunctionArguments.js' {
  declare module.exports: $Exports<'stylelint/src/utils/blurFunctionArguments'>;
}
declare module 'stylelint/src/utils/configurationError.js' {
  declare module.exports: $Exports<'stylelint/src/utils/configurationError'>;
}
declare module 'stylelint/src/utils/cssDeclarationIsMap.js' {
  declare module.exports: $Exports<'stylelint/src/utils/cssDeclarationIsMap'>;
}
declare module 'stylelint/src/utils/cssFunctionArguments.js' {
  declare module.exports: $Exports<'stylelint/src/utils/cssFunctionArguments'>;
}
declare module 'stylelint/src/utils/cssNodeContextLookup.js' {
  declare module.exports: $Exports<'stylelint/src/utils/cssNodeContextLookup'>;
}
declare module 'stylelint/src/utils/cssRuleHasSelectorEndingWithColon.js' {
  declare module.exports: $Exports<'stylelint/src/utils/cssRuleHasSelectorEndingWithColon'>;
}
declare module 'stylelint/src/utils/cssStatementBlockString.js' {
  declare module.exports: $Exports<'stylelint/src/utils/cssStatementBlockString'>;
}
declare module 'stylelint/src/utils/cssStatementHasBlock.js' {
  declare module.exports: $Exports<'stylelint/src/utils/cssStatementHasBlock'>;
}
declare module 'stylelint/src/utils/cssStatementHasEmptyBlock.js' {
  declare module.exports: $Exports<'stylelint/src/utils/cssStatementHasEmptyBlock'>;
}
declare module 'stylelint/src/utils/cssStatementStringBeforeBlock.js' {
  declare module.exports: $Exports<'stylelint/src/utils/cssStatementStringBeforeBlock'>;
}
declare module 'stylelint/src/utils/cssWordIsVariable.js' {
  declare module.exports: $Exports<'stylelint/src/utils/cssWordIsVariable'>;
}
declare module 'stylelint/src/utils/declarationValueIndexOffset.js' {
  declare module.exports: $Exports<'stylelint/src/utils/declarationValueIndexOffset'>;
}
declare module 'stylelint/src/utils/findMediaContext.js' {
  declare module.exports: $Exports<'stylelint/src/utils/findMediaContext'>;
}
declare module 'stylelint/src/utils/index.js' {
  declare module.exports: $Exports<'stylelint/src/utils/index'>;
}
declare module 'stylelint/src/utils/isAutoprefixable.js' {
  declare module.exports: $Exports<'stylelint/src/utils/isAutoprefixable'>;
}
declare module 'stylelint/src/utils/isLowerSpecificity.js' {
  declare module.exports: $Exports<'stylelint/src/utils/isLowerSpecificity'>;
}
declare module 'stylelint/src/utils/isSingleLineString.js' {
  declare module.exports: $Exports<'stylelint/src/utils/isSingleLineString'>;
}
declare module 'stylelint/src/utils/isValidHex.js' {
  declare module.exports: $Exports<'stylelint/src/utils/isValidHex'>;
}
declare module 'stylelint/src/utils/isWhitespace.js' {
  declare module.exports: $Exports<'stylelint/src/utils/isWhitespace'>;
}
declare module 'stylelint/src/utils/matchesStringOrRegExp.js' {
  declare module.exports: $Exports<'stylelint/src/utils/matchesStringOrRegExp'>;
}
declare module 'stylelint/src/utils/mediaQueryParamIndexOffset.js' {
  declare module.exports: $Exports<'stylelint/src/utils/mediaQueryParamIndexOffset'>;
}
declare module 'stylelint/src/utils/optionsHaveException.js' {
  declare module.exports: $Exports<'stylelint/src/utils/optionsHaveException'>;
}
declare module 'stylelint/src/utils/optionsHaveIgnored.js' {
  declare module.exports: $Exports<'stylelint/src/utils/optionsHaveIgnored'>;
}
declare module 'stylelint/src/utils/rawNodeString.js' {
  declare module.exports: $Exports<'stylelint/src/utils/rawNodeString'>;
}
declare module 'stylelint/src/utils/report.js' {
  declare module.exports: $Exports<'stylelint/src/utils/report'>;
}
declare module 'stylelint/src/utils/ruleMessages.js' {
  declare module.exports: $Exports<'stylelint/src/utils/ruleMessages'>;
}
declare module 'stylelint/src/utils/styleSearch.js' {
  declare module.exports: $Exports<'stylelint/src/utils/styleSearch'>;
}
declare module 'stylelint/src/utils/validateOptions.js' {
  declare module.exports: $Exports<'stylelint/src/utils/validateOptions'>;
}
declare module 'stylelint/src/utils/whitespaceChecker.js' {
  declare module.exports: $Exports<'stylelint/src/utils/whitespaceChecker'>;
}
